type shadowType = {
  name: string;
  link: string;
  imageShadow: string;
  imageAnswer: string;
  answers: Record<string, string>;
  right: string;
  wrong: string;
};

export const shadowsData: Record<string, shadowType> = {
  1: {
    name: "скульптура",
    link: "https://aliexpress.ru/item/1005006014505297.html?sku_id=12000035328274175&spm=a2g2w.productlist.search_results.2.61122719FFV5y5",
    imageShadow: "png/shadows/question/1.png",
    imageAnswer: "png/shadows/answer/1.png",
    answers: {
      1: "ночной светильник",
      2: "скульптура",
      3: "электрическая соковыжималка",
    },
    right: "Воу, да ты ценитель прекрасного!",
    wrong: "Не расстраивайся! Я тоже в этом искусстве ничего не понимаю...",
  },
  2: {
    name: "швейная мини-машина",
    link: "https://aliexpress.ru/item/32844273795.html?sku_id=65164426810&spm=a2g2w.productlist.search_results.14.776f63baQMLwMZ",
    imageShadow: "png/shadows/question/2.png",
    imageAnswer: "png/shadows/answer/2.png",
    answers: {
      1: "швейная мини-машина",
      2: "степлер",
      3: 'игрушка-кусачка "голова крокодила"',
    },
    right: "Правильно! Ты, кажется, любишь рукодельничать?",
    wrong: "Согласен, не очень-то и похоже на швейную машинку...",
  },
  3: {
    name: "открывашка для банок",
    link: "https://aliexpress.ru/item/32695039585.html?spm=a2g2w.detail.rcmdprod.5.11404fe5bl69Qg&mixer_rcmd_bucket_id=aerabtestalgoRecommendAbV4_controlRu1&ru_algo_pv_id=052dfd-40a3c7-9fc34d-d8732d&scenario=pcDetailBottomMoreThisSeller&sku_id=64744449660&traffic_source=recommendation&type_rcmd=core",
    imageShadow: "png/shadows/question/3.png",
    imageAnswer: "png/shadows/answer/3.png",
    answers: {
      1: 'форма для запекания "снеговик"',
      2: "открывашка для банок",
      3: "стопер для двери",
    },
    right: "Моя бабуля такой банки с вареньем закатывает!",
    wrong: "Я и сам бы не угадал!",
  },
  4: {
    name: "мини-овощичистка",
    link: "https://aliexpress.ru/item/1005005939712196.html?spm=a2g2w.productlist.0.0.6a804aa68sajEv&sku_id=12000034941763826",
    imageShadow: "png/shadows/question/4.png",
    imageAnswer: "png/shadows/answer/4.png",
    answers: {
      1: "мини-овощичистка",
      2: "флешка",
      3: "скребок для языка",
    },
    right: "Интересно, что за мини-людям нужна такая мини-овощечистка?",
    wrong: "Чего-о-о? Да это было нереально угадать!",
  },
  5: {
    name: "пресс для зубной пасты",
    link: "https://aliexpress.ru/item/1005002598649368.html?spm=a2g2w.detail.rcmdprod.0.68a76994ySVYNw&mixer_rcmd_bucket_id=aerabtestalgoRecommendAbV4_controlRu1&ru_algo_pv_id=052dfd-40a3c7-9fc34d-5a5cd2&scenario=pcDetailBottomMoreThisSeller&sku_id=12000021329147644&traffic_source=recommendation&type_rcmd=core",
    imageShadow: "png/shadows/question/5.png",
    imageAnswer: "png/shadows/answer/5.png",
    answers: {
      1: "лонг-борд",
      2: "пресс для зубной пасты",
      3: "ластик в форме лягушки",
    },
    right: "У меня нет пресса, но есть пресс для пасты! А у тебя?",
    wrong: "Почему эта штука так похожа на моего племянника?!",
  },
  6: {
    name: "точилка для кухонных ножей",
    link: "https://aliexpress.ru/item/1005005246816437.html?sku_id=12000032349311542&spm=a2g2w.productlist.search_results.12.26804aa6Erpo3J",
    imageShadow: "png/shadows/question/6.png",
    imageAnswer: "png/shadows/answer/6.png",
    answers: {
      1: "точилка для кухонных ножей",
      2: "утюг нового поколения",
      3: "кронштейн для циркулярной пилы",
    },
    right: "На твоей кухне ночи всегда заточены!",
    wrong: "По-моему, это бред... Реально на утюг похоже!",
  },
  7: {
    name: "usb-светильник",
    link: "https://aliexpress.ru/item/1005003323435265.html?spm=a2g2w.detail.rcmdprod.0.305d73efNTgMSH&mixer_rcmd_bucket_id=aerabtestalgoRecommendAbV4_controlRu1&ru_algo_pv_id=052dfd-40a3c7-9fc34d-6f25ef&scenario=pcDetailBottomMoreThisSeller&sku_id=12000025210092939&traffic_source=recommendation&type_rcmd=core",
    imageShadow: "png/shadows/question/7.png",
    imageAnswer: "png/shadows/answer/7.png",
    answers: {
      1: "автомобильный ключ для ремонта шин",
      2: "пауэр банк",
      3: "usb-светильник",
    },
    right: "Тебя не проведёшь!",
    wrong: "Мда, Ali Coins заработать не так просто...",
  },
  8: {
    name: "формочка для снежков",
    link: "https://aliexpress.ru/item/1005003578810562.html?spm=a2g2w.detail.rcmdprod.4.17082cc2ZuqFIL&mixer_rcmd_bucket_id=aerabtestalgoRecommendAbV4_controlRu1&ru_algo_pv_id=052dfd-40a3c7-9fc34d-806551&scenario=pcDetailBottomMoreThisSeller&sku_id=12000026355630598&traffic_source=recommendation&type_rcmd=core",
    imageShadow: "png/shadows/question/8.png",
    imageAnswer: "png/shadows/answer/8.png",
    answers: {
      1: "формочка для снежков",
      2: "силиконовая ложка для готовки",
      3: "резак для ветвей",
    },
    right: "Молодец! Скорее бы поиграть в снежки!",
    wrong: "Вы, земляне, правда не можете слепить снежок руками?!",
  },
  9: {
    name: "спинер",
    link: "https://aliexpress.ru/item/1005004077303490.html?sku_id=12000027964497228&spm=a2g2w.productlist.search_results.12.16d44aa6A9m6YU",
    imageShadow: "png/shadows/question/9.png",
    imageAnswer: "png/shadows/answer/9.png",
    answers: {
      1: "заколка-цветочек",
      2: "наклейка на колёсный диск",
      3: "спинер",
    },
    right: "О-о-о, эту штуку вспомнят только легенды...",
    wrong:
      "Объясните мне кто-нибудь, что такое спинер и как им пользоваться???",
  },
  10: {
    name: "многофункциональный фонарик",
    link: "https://aliexpress.ru/item/1005002702723581.html?spm=a2g2w.home.10009201.114.4ab55931oe2gAk&mixer_rcmd_bucket_id=aerabtestalgoRecommendAbV4_testAllShallowLongSerpsInvertRank&ru_algo_pv_id=ac06cb-23d4bc-64eb7b-9725ba&scenario=pcBestMore2Love&sku_id=12000032575195057&traffic_source=recommendation&type_rcmd=affiliate",
    imageShadow: "png/shadows/question/10.png",
    imageAnswer: "png/shadows/answer/10.png",
    answers: {
      1: "закладка для книги",
      2: "якорь для лодки",
      3: "многофункциональный фонарик",
    },
    right: "Ого! Кто-то проходил курсы скаутов?",
    wrong: "Ну и куда с таким фонариком пойдёшь?!",
  },
  11: {
    name: "щётка для лица",
    link: "https://aliexpress.ru/item/1005004210027133.html?sku_id=12000028390239499&spm=a2g2w.productlist.search_results.6.20b94aa6EZpR7h",
    imageShadow: "png/shadows/question/11.png",
    imageAnswer: "png/shadows/answer/11.png",
    answers: {
      1: "портативная колонка",
      2: "плюшевая игрушка брокколи",
      3: "щётка для лица",
    },
    right: "Молодец! Уход за собой -- это важно!",
    wrong: "Не знаю, по-моему на брокколи реально похоже",
  },
  12: {
    name: "телефон-туфля",
    link: "https://aliexpress.ru/item/1005005486738931.html?sku_id=12000033274232040&spm=a2g2w.productlist.search_results.10.25ce23e5hyVBUB",
    imageShadow: "png/shadows/question/12.png",
    imageAnswer: "png/shadows/answer/12.png",
    answers: {
      1: "женская туфля",
      2: "телефон-туфля",
      3: "детская горка",
    },
    right: "Алло, это самый умный человек во вселенной?",
    wrong: "Любите вы из обычных вещей сделать какую-то кринжуху...",
  },
  13: {
    name: "ободок для волос",
    link: "https://aliexpress.ru/item/1005004857669059.html?sku_id=12000030770787742&spm=a2g2w.productlist.search_results.15.390d4aa6CW9cLy",
    imageShadow: "png/shadows/question/13.png",
    imageAnswer: "png/shadows/answer/13.png",
    answers: {
      1: "электро-коса",
      2: "позолоченная ручка двери",
      3: "ободок для волос",
    },
    right: "Он наверняка уже лежит у тебя в корзине на AliExpress",
    wrong: "Неверно, но всё равно ты супер!",
  },
  14: {
    name: "электрическая капельница для полива",
    link: "https://aliexpress.ru/item/1005003516631968.html?sku_id=12000026142492904&spm=a2g2w.productlist.search_results.1.77e34aa6HSIwly",
    imageShadow: "png/shadows/question/14.png",
    imageAnswer: "png/shadows/answer/14.png",
    answers: {
      1: "юла",
      2: "роликовый тренажёр для фитнеса",
      3: "электрическая капельница для полива",
    },
    right: "Садоводство - это круто!",
    wrong: "Да уж, прошла любовь, завяли помидоры...",
  },
  15: {
    name: "молоток дробительный",
    link: "https://aliexpress.ru/item/1005005221812242.html?spm=a2g2w.detail.rcmdprod.24.61873297rgx2WR&sku_id=12000032243262327",
    imageShadow: "png/shadows/question/15.png",
    imageAnswer: "png/shadows/answer/15.png",
    answers: {
      1: "молоток дробительный",
      2: "конструктор-башня",
      3: "дрель-шуруповёрт",
    },
    right: "Да ты мастер на все руки!",
    wrong: "Ладно, это было сложно",
  },
  16: {
    name: "подушка-антистресс",
    link: "https://aliexpress.ru/item/1005005825129005.html?spm=a2g2w.detail.rcmdprod.8.680d54cd12uYPg&mixer_rcmd_bucket_id=aerabtestalgoRecommendAbV4_testCisFiltering&ru_algo_pv_id=e605ad-40a3c7-9fc34d-7d79d4&scenario=pcDetailBottomMoreThisSeller&sku_id=12000035070988884&traffic_source=recommendation&type_rcmd=core",
    imageShadow: "png/shadows/question/16.png",
    imageAnswer: "png/shadows/answer/16.png",
    answers: {
      1: "дизайнерское кресло",
      2: "подушка-антистресс",
      3: "детская насадка на унитаз",
    },
    right: "Хотел бы я работать за твоим столом!",
    wrong: "Я вообще решил, что это для массажа",
  },
  17: {
    name: "детская шапка для купания",
    link: "https://aliexpress.ru/item/32830433027.html?spm=a2g2w.detail.rcmdprod.3.2e7135d5058jCc&mixer_rcmd_bucket_id=aerabtestalgoRecommendAbV4_controlRu1&ru_algo_pv_id=052dfd-476f2e-2bf73b-00d343&scenario=pcDetailBottomMoreOtherSeller&sku_id=65039925962&traffic_source=recommendation&type_rcmd=core",
    imageShadow: "png/shadows/question/17.png",
    imageAnswer: "png/shadows/answer/17.png",
    answers: {
      1: "слюнявчик",
      2: "детская шапка для купания",
      3: "фитнес-трекер",
    },
    right: "Я бы такую шапку и не только для купания надел!",
    wrong: "Какая шапка? Это же летающая тарелка, у меня такая же!",
  },
  18: {
    name: "варежка для пары",
    link: "https://aliexpress.ru/item/32933530478.html?sku_id=12000025853754614&spm=a2g2w.productlist.search_results.0.670b4aa6yVOKzx",
    imageShadow: "png/shadows/question/18.png",
    imageAnswer: "png/shadows/answer/18.png",
    answers: {
      1: "подушка для путешествий",
      2: "варежка для пары",
      3: "игрушка мягкая радуга",
    },
    right: "Ой, у нас тут романтики!",
    wrong: "Иу, неудобно как-то...",
  },
  19: {
    name: "чехол на телефон",
    link: "https://aliexpress.ru/item/1005005934716722.html?sku_id=12000034918740819&spm=a2g2w.productlist.search_results.2.22814aa6V2mmDZ",
    imageShadow: "png/shadows/question/19.png",
    imageAnswer: "png/shadows/answer/19.png",
    answers: {
      1: "чехол на телефон",
      2: "пенал",
      3: "кухонный нож",
    },
    right: "Круто таким отпугивать злодеев",
    wrong: "Ой, только не бей меня!",
  },
  20: {
    name: "футляр для зубочисток",
    link: "https://aliexpress.ru/item/1005003356635852.html?sku_id=12000025377250205&spm=a2g2w.productlist.search_results.4.297d4aa6BGOt3E",
    imageShadow: "png/shadows/question/20.png",
    imageAnswer: "png/shadows/answer/20.png",
    answers: {
      1: "губная помада",
      2: "ожерелье-клык",
      3: "футляр для зубочисток",
    },
    right: "Признавайся, у тебя там встроенный рентген?",
    wrong: "Что угодно, только не футляр для зубочисток!",
  },
  21: {
    name: "детский зонт-плащ",
    link: "https://aliexpress.ru/item/1005005557769665.html?sku_id=12000033534382671&spm=a2g2w.productlist.search_results.14.1b164aa63HxKz5",
    imageShadow: "png/shadows/question/21.png",
    imageAnswer: "png/shadows/answer/21.png",
    answers: {
      1: "крышка для блендера",
      2: "детский зонт-плащ",
      3: "силиконовая присоска",
    },
    right: "Ты точно с этой планеты?",
    wrong: "Если это зонт, то я балерина...",
  },
  22: {
    name: "бокал-насадка на бутылку",
    link: "https://aliexpress.ru/item/32980445054.html?sku_id=12000031969731378",
    imageShadow: "png/shadows/question/22.png",
    imageAnswer: "png/shadows/answer/22.png",
    answers: {
      1: "лампочка",
      2: "колокольчик",
      3: "бокал-насадка на бутылку",
    },
    right: "Вот это наш вариант!",
    wrong: "Ой, ну и ладно! Мы из нормальных бокалов пьём",
  },
  23: {
    name: "шпажки для еды в виде муравья",
    link: "https://aliexpress.ru/item/32959866342.html?sku_id=66405499661&spm=a2g2w.productlist.search_results.3.60584aa6JyRmJA",
    imageShadow: "png/shadows/question/23.png",
    imageAnswer: "png/shadows/answer/23.png",
    answers: {
      1: "протестующий муравей",
      2: "шпажки для еды в виде муравья",
      3: "муравей-пылесос",
    },
    right: "Я думал, ты никогда не угадаешь!",
    wrong: "Протестую, прям как этот муравей!",
  },
  24: {
    name: "игрушка брызгалка",
    link: "https://aliexpress.ru/item/1005004288603495.html?sku_id=12000028642902522&spm=a2g2w.productlist.search_results.9.4c7e4aa6d5egxg",
    imageShadow: "png/shadows/question/24.png",
    imageAnswer: "png/shadows/answer/24.png",
    answers: {
      1: "адаптер SD карты",
      2: "зажигалка",
      3: "игрушка брызгалка",
    },
    right: "Угадал! Любишь прикалываться над друзьями??",
    wrong: "Ладно, это был вопрос с подвохом!",
  },
};
